### ISSUE TITLE
Remove ldconfig command

### ISSUE THREAD

**Issue by W-Mohammed** [W-Mohammed/docker-repast-hpc#4]
Thanks to a previous bug identified by @nietoga, the `ubuntu`-based rhpc image seems to work fine without the `ldconfig` command. Hence, it would make more sense to remove it.

**Comment by nietoga** [comment]
Hi @W-Mohammed, I'm sorry I made suggestions without knowing your use-case for this container. In my case I'm interested in building the demos present on https://repast.github.io/hpc_tutorial/main.html and executing them. Without the `build-essential` package I could not compile the demos and without the `ldconfig` command properly configured I can't execute them because the libraries are not found. 

<img width="980" alt="image" src="https://user-images.githubusercontent.com/30280788/194073926-c629d579-d01f-490b-90b5-8a420c80aa3d.png">

The other alternative is using the `LD_LIBRARY_PATH` variable for execution but I think using `ldconfig` is more elegant.

Example:
```
LD_LIBRARY_PATH=/root/sfw/boost-1_61_0/lib:/root/sfw/repast_hpc-2.3.1/lib:/root/sfw/netcdf-4.2.1.1/lib:/root/sfw/netcdf-cxx-4.2/lib:$LD_LIBRARY_PATH ./Demo_00.exe
```

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/30280788/194075182-361f5dbe-6c49-4f12-a792-2f80041b0eb1.png">

I'm using the following env file for demos

```
MPICXX=mpicxx -std=c++11 

BOOST_INCLUDE=-I/root/sfw/boost-1_61_0/include/
BOOST_LIB_DIR=-L/root/sfw/boost-1_61_0/lib/
BOOST_LIBS=-lboost_mpi-mt -lboost_serialization-mt -lboost_system-mt -lboost_filesystem-mt

REPAST_HPC_INCLUDE=-I/root/sfw/repast_hpc-2.3.1/include/
REPAST_HPC_LIB_DIR=-L/root/sfw/repast_hpc-2.3.1/lib/
REPAST_HPC_LIB=-lrepast_hpc-2.3.1
```

**Comment by W-Mohammed** [comment]
This feedback is excellent. Thank you so much, @nietoga.

I have used rhpc on a virtual machine in a recent project, but I have not tested this container beyond running the demo examples that ship with rhpc, and interesting enough, they work fine without the `ldconfing`.

I will add the `ldconfing` command back into the dockerfile and update the image!

Thanks, @nietoga!

**Comment by W-Mohammed** [comment]
@nietoga, I understand that you are building your image locally; but can I ask that you please test the image hosted on `ghcr`.  Let me know if you can run the demos you mentioned earlier!

```
docker pull ghcr.io/w-mohammed/repast-hpc:2.3.1-ubuntu22.10-v1.2
```

**Comment by nietoga** [comment]
> I have used rhpc on a virtual machine in a recent project, but I have not tested this container beyond running the demo examples that ship with rhpc, and interesting enough, they work fine without the `ldconfing`.

Demos up to `Demo_00/Step_03` work fine without `ldconfig` because they're only including headers from the standard library.

> @nietoga, I understand that you are building your image locally; but can I ask that you please test the image hosted on `ghcr`. Let me know if you can run the demos you mentioned earlier!

Regarding this, I can't. I have no permissions to pull your image or that's what I understood when I tried doing so in the past.

Reference: https://stackoverflow.com/a/70398791

**Comment by W-Mohammed** [comment]
> 



> > I have used rhpc on a virtual machine in a recent project, but I have not tested this container beyond running the demo examples that ship with rhpc, and interesting enough, they work fine without the `ldconfing`.
> 
> Demos up to `Demo_00/Step_03` work fine without `ldconfig` because they're only including headers from the standard library.
> 
> > @nietoga, I understand that you are building your image locally; but can I ask that you please test the image hosted on `ghcr`. Let me know if you can run the demos you mentioned earlier!
> 
> Regarding this, I can't. I have no permissions to pull your image or that's what I understood when I tried doing so in the past.
> 
> Reference: https://stackoverflow.com/a/70398791

Thanks for the extensive analysis. 
Sorry, I did not realise I had not removed image restrictions on `ghcr.io`. I have just updated the visibility, and you should be able to pull it!

**Comment by nietoga** [comment]
Hi @W-Mohammed I pulled image `ghcr.io/w-mohammed/repast-hpc:2.3.1-ubuntu22.10-v1.2` and somehow it works.

- I say "somehow" because it's weird it can find the libraries without using `ldconfig` 

<img width="885" alt="image" src="https://user-images.githubusercontent.com/30280788/194117641-63d77ef5-20c3-47bf-9276-4e01917534a5.png">

File being compiled:

```cpp
#include <stdio.h>
#include <boost/mpi.hpp>

int main(int argc, char** argv){
	
	boost::mpi::environment env(argc, argv);
	boost::mpi::communicator world;

	if(world.rank() == 0){
	    printf("Hello, world! I'm rank %d\n", world.rank());
	}
	else{
	    printf("Hmm...\n");
	}
	
}
```

**Comment by W-Mohammed** [comment]
Hi @nietoga,

Thanks for the extensive testing. I guess I did not clarify that I built the image I asked you to test using the `ldconfig` command.

I will close this issue now, but let me know if it is still a problem!

**Comment by nietoga** [comment]
Hi @W-Mohammed 
Ok, thanks for the clarification. I was really confused there.
It was nice collaborating with you. Thanks again for making this repository public, it's been useful to me.
